### 
POST http://localhost:3000
Content-Type: application/json

{
    "name": "Larry",
    "location": "Georgia",
    "points": 100
}

###

###
GET http://localhost:3000
###

GET http://localhost:3000/2

###

GET http://localhost:3000/rewards

###


PUT http://localhost:3000/2
Content-Type: application/json

{
    "name": "Lucy",
    "location": "Paris",
    "points": 100
}
###
GET http://localhost:3000/8/rewards

###

POST http://localhost:3000/3/rewards
Content-Type: application/json

{
    "user_id": 8,
    "reward_id": 1
}

### 
GET http://localhost:3000/admin