###
GET http://localhost:3000/setup

###

### 
POST http://localhost:3000
Content-Type: application/json

{
    "name": "Frank",
    "location": "Georgia"
}

###

###
GET http://localhost:3000
###

GET http://localhost:3000/3

###

PUT http://localhost:3000/2
Content-Type: application/json

{
    "name": "Lucy",
    "location": "Paris"
}
###
